language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install libinsighttoolkit3-dev
  - sudo apt-get install libgdcm2-dev
  - mkdir build
  - cd build
  - cmake ..
script: cmake --build . && ctest
